### ISSUE TITLE
redeem_process.py - sufficient tokens but fails

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/asset-mapping#10]
Definitely had enough tokes but says insufficient :( not due to inflation issue as well within timeframe

{'serialno': '666666', 'year': '2019', 'manufacturer': 'Dan', 'mass': 400.01, 'tokens': 4002.58358695}

Redemption transaction total tokens: 4002.58358695 is insufficient

Screenshots
https://www.dropbox.com/s/h3vk7zdtf87hs72/Screenshot%202019-06-07%2012.00.05.png?dl=0
https://www.dropbox.com/s/v233l2gyvinzzsc/Screenshot%202019-06-07%2012.03.23.png?dl=0

**Comment by tomt1664** [comment]
fixed with 6c48dfe08a8f6461567e9d3f2f46ba88765cd983
