### ISSUE TITLE
Redeem_process.py error - asset found error - Exception: Error in RPC call: {'code': -5, 'message': 'Invalid private key encoding'} 

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/asset-mapping#16]
Last login: Fri Jun 21 12:25:40 on ttys002
cryptopolys-MacBook-Pro:~ cryptopoly$ /Users/cryptopoly/****\ Scripts/R.1\ Redeem\ Process.command ; exit;
Redemption transaction processing
Load the mapping object - connecting to S3
    Timestamp: 1561115242.831059 (Fri Jun 21 12:07:22 2019)
    Signatures verified
 
Load the redeem list object - rassets.json
 
Connecting to Ocean client
 
Token ratio = 0.09999782016 at block 1172
 
Enter redeemed asset reference: 100009-2019-****
 
Asset mass: 400.000
Required tokens: 4000.08719564
 
Read in redemption (freeze) transaction
 
    Redemption transaction valid
 
    Redemption transaction has sufficient tokens
 
ALL REDEMPTION CHECKS PASSED
Locking asset in redeem list
Add redemption transaction addresses to the freezelist
 
Traceback (most recent call last):
  File "redeem_process.py", line 166, in <module>
    ocean.call('importprivkey',frzlistprivkey,"freezeasset",True)
  File "/usr/local/lib/python3.7/site-packages/amap-0.1-py3.7.egg/amap/rpchost.py", line 31, in call
Exception: Error in RPC call: {'code': -5, 'message': 'Invalid private key encoding'}
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by tomt1664** [comment]
Outdated private key encoding. Resolved.
