### ISSUE TITLE
Redeem_process.py - error

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/asset-mapping#17]
Ran redeem_process.py, all redemption checks passed but failed :(

Last login: Fri Jun 21 14:12:30 on ttys002
cryptopolys-MacBook-Pro:~ cryptopoly$ /Users/cryptopoly/****\ Scripts/Redeem\ Process.command ; exit;
Redemption transaction processing
Load the mapping object - connecting to S3
    Timestamp: 1561122440.308247 (Fri Jun 21 14:07:20 2019)
    Signatures verified
 
Load the redeem list object - rassets.json
 
Connecting to Ocean client
 
Token ratio = 0.09999759070 at block 1277
 
Enter redeemed asset reference: 100017-2019-****
 
Asset mass: 400.000
Required tokens: 4000.09637425
 
Read in redemption (freeze) transaction
 
    Redemption transaction valid
 
    Redemption transaction has sufficient tokens
 
ALL REDEMPTION CHECKS PASSED
Locking asset in redeem list
Add redemption transaction addresses to the freezelist
 
 
Policy asset UTXOs found: 100
Traceback (most recent call last):
  File "redeem_process.py", line 199, in <module>
    freezetx_send = ocean.call('sendrawtransaction',freezetx_signed["hex"])
  File "/usr/local/lib/python3.7/site-packages/amap-0.1-py3.7.egg/amap/rpchost.py", line 31, in call
Exception: Error in RPC call: {'code': -26, 'message': '16: bad-txns-in-ne-out'}
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by tomt1664** [comment]
The freeze asset had changed in a testnet restart. Resolved.
