### ISSUE TITLE
burnlist.py error - IndexError: list index out of range

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/asset-mapping#18]
Burnlist registration failed. Everything else seemed OK. Perhaps this is because the only tx related to this address is the issuance (cannot currently send any tokens so trying to issue and redeem in the same hour) :(

Last login: Fri Jun 21 16:39:14 on ttys002
cryptopolys-MacBook-Pro:~ cryptopoly$ /Users/cryptopoly/xxxx\ Scripts/Burnlist\ Update.command ; exit;
burnlist control wallet
 
Connecting to Ocean client
 
Add address to burnlist:
Enter address: 2dbuocQrSJdAGYnqzBfi3AbNZdqUVfJLcDE
 
Policy asset UTXOs found: 0
Traceback (most recent call last):
  File "burnlist.py", line 55, in <module>
    txin = txinlst[0]
IndexError: list index out of range
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by tomt1664** [comment]
This was due to an outdated burn asset address (which was changed on a testnet restart).
